# Generated by Django 3.2.5 on 2021-07-28 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 29, 0, 18, 19, 637329))),
            ],
        ),
    ]
