# Generated by Django 3.2.5 on 2021-07-28 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 29, 0, 46, 7, 57084)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
