# Generated by Django 3.2.5 on 2021-07-29 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_todo_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 29, 12, 3, 40, 270967)),
        ),
    ]
